// Copyright (c) 2010 Satoshi Nakamoto
// Copyright (c) 2009-2022 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <key_io.h>
#include <outputtype.h>
#include <pubkey.h>
#include <rpc/protocol.h>
#include <rpc/request.h>
#include <rpc/server.h>
#include <rpc/util.h>
#include <script/descriptor.h>
#include <script/pqm.h>
#include <script/script.h>
#include <script/signingprovider.h>
#include <tinyformat.h>
#include <univalue.h>
#include <util/check.h>
#include <util/strencodings.h>

#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <vector>
#include <algorithm>

static constexpr auto LEGACY_MULTISIG_DISABLED_ERROR =
    "BTX PQ policy: legacy multisig RPCs are disabled; use P2MR descriptors";

struct PQMultisigKey {
    PQAlgorithm algo;
    std::vector<unsigned char> pubkey;
};

static bool ParsePQMultisigKeyString(const std::string& key_str, PQMultisigKey& out, std::string& error)
{
    std::string body = key_str;
    bool wrapped_slh = false;
    if (body.rfind("pk_slh(", 0) == 0 && body.size() > 8 && body.back() == ')') {
        wrapped_slh = true;
        body = body.substr(7, body.size() - 8);
    }

    if (!IsHex(body)) {
        error = strprintf("Invalid PQ pubkey '%s' (expected hex or pk_slh(hex))", key_str);
        return false;
    }
    std::vector<unsigned char> pubkey = ParseHex(body);
    if (wrapped_slh) {
        if (pubkey.size() != SLHDSA128S_PUBKEY_SIZE) {
            error = strprintf("pk_slh() key must be %u bytes, got %u bytes", SLHDSA128S_PUBKEY_SIZE, pubkey.size());
            return false;
        }
        out.algo = PQAlgorithm::SLH_DSA_128S;
        out.pubkey = std::move(pubkey);
        return true;
    }

    if (pubkey.size() == MLDSA44_PUBKEY_SIZE) {
        out.algo = PQAlgorithm::ML_DSA_44;
        out.pubkey = std::move(pubkey);
        return true;
    }
    if (pubkey.size() == SLHDSA128S_PUBKEY_SIZE) {
        out.algo = PQAlgorithm::SLH_DSA_128S;
        out.pubkey = std::move(pubkey);
        return true;
    }

    error = strprintf("Unsupported PQ pubkey size %u bytes", pubkey.size());
    return false;
}

static std::string RenderPQMultisigKey(const PQMultisigKey& key)
{
    if (key.algo == PQAlgorithm::SLH_DSA_128S) {
        return strprintf("pk_slh(%s)", HexStr(key.pubkey));
    }
    return HexStr(key.pubkey);
}

static RPCHelpMan validateaddress()
{
    return RPCHelpMan{
        "validateaddress",
        "\nReturn information about the given BTX address.\n",
        {
            {"address", RPCArg::Type::STR, RPCArg::Optional::NO, "The BTX address to validate"},
            {"address_type", RPCArg::Type::STR, RPCArg::Optional::OMITTED, "DEPRECATED", RPCArgOptions{.hidden=true}},
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "",
            {
                {RPCResult::Type::BOOL, "isvalid", "If the address is valid or not"},
                {RPCResult::Type::STR, "address", /*optional=*/true, "The BTX address validated"},
                {RPCResult::Type::STR_HEX, "scriptPubKey", /*optional=*/true, "The hex-encoded output script generated by the address"},
                {RPCResult::Type::BOOL, "isscript", /*optional=*/true, "If the key is a script"},
                {RPCResult::Type::BOOL, "iswitness", /*optional=*/true, "If the address is a witness address"},
                {RPCResult::Type::NUM, "witness_version", /*optional=*/true, "The version number of the witness program"},
                {RPCResult::Type::STR_HEX, "witness_program", /*optional=*/true, "The hex value of the witness program"},
                {RPCResult::Type::STR, "error", /*optional=*/true, "Error message, if any"},
                {RPCResult::Type::NUM, "error_index", /*optional=*/true, "DEPRECATED. The index of the first likely error location, if known"},
                {RPCResult::Type::ARR, "error_locations", /*optional=*/true, "Indices of likely error locations in address, if known (e.g. Bech32 errors)",
                    {
                        {RPCResult::Type::NUM, "index", "index of a potential error"},
                    }},
            }
        },
        RPCExamples{
            HelpExampleCli("validateaddress", "\"" + EXAMPLE_ADDRESS[0] + "\"") +
            HelpExampleRpc("validateaddress", "\"" + EXAMPLE_ADDRESS[0] + "\"")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            std::string error_msg;
            std::vector<int> error_locations;
            CTxDestination dest = DecodeDestination(request.params[0].get_str(), error_msg, &error_locations);

            // Merely validate address_type is an actual address type, so we don't silently ignore potential future parameters
            if (!request.params[1].isNull()) {
                if (!ParseOutputType(request.params[1].get_str())) {
                    throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("Unknown address type '%s'", request.params[1].get_str()));
                }
            }

            const bool isValid = IsValidDestination(dest);
            CHECK_NONFATAL(isValid == error_msg.empty());

            UniValue ret(UniValue::VOBJ);
            ret.pushKV("isvalid", isValid);
            if (isValid) {
                std::string currentAddress = EncodeDestination(dest);
                ret.pushKV("address", currentAddress);

                CScript scriptPubKey = GetScriptForDestination(dest);
                ret.pushKV("scriptPubKey", HexStr(scriptPubKey));

                UniValue detail = DescribeAddress(dest);
                ret.pushKVs(std::move(detail));
            } else {
                if (!error_locations.empty()) {
                    ret.pushKV("error_index", error_locations.at(0));
                }
                UniValue error_indices(UniValue::VARR);
                for (int i : error_locations) error_indices.push_back(i);
                ret.pushKV("error_locations", std::move(error_indices));
                ret.pushKV("error", error_msg);
            }

            return ret;
        },
    };
}

static RPCHelpMan createmultisig()
{
    return RPCHelpMan{"createmultisig",
        "\nCreates a post-quantum P2MR multisig address with n signatures of m keys required.\n"
        "Only PQ pubkeys are accepted (ML-DSA-44 hex, SLH-DSA hex, or pk_slh(hex)).\n"
        "Legacy (secp256k1) multisig remains disabled.\n",
        {
            {"nrequired", RPCArg::Type::NUM, RPCArg::Optional::NO, "The number of required signatures out of the n keys."},
            {"keys", RPCArg::Type::ARR, RPCArg::Optional::NO, "The hex-encoded public keys.",
                {
                    {"key", RPCArg::Type::STR, RPCArg::Optional::OMITTED, "PQ pubkey as ML-DSA hex, SLH-DSA hex, or pk_slh(hex)"},
                }},
            {"options|address_type", {RPCArg::Type::OBJ_NAMED_PARAMS, RPCArg::Type::STR}, RPCArg::Optional::OMITTED, "",
                {
                    {"address_type", RPCArg::Type::STR, RPCArg::Default{"p2mr"}, "The address type to use. Only \"p2mr\" is supported.", RPCArgOptions{.also_positional = true}},
                    {"sort", RPCArg::Type::BOOL, RPCArg::Default{false}, "Whether to sort public keys according to BIP67."},
                },
                RPCArgOptions{.oneline_description="options"}},
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "",
            {
                {RPCResult::Type::STR, "address", "The value of the new multisig address."},
                {RPCResult::Type::STR_HEX, "redeemScript", "The string value of the hex-encoded redemption script."},
                {RPCResult::Type::STR, "descriptor", "The descriptor for this multisig"},
                {RPCResult::Type::ARR, "warnings", /*optional=*/true, "Any warnings resulting from the creation of this multisig",
                {
                    {RPCResult::Type::STR, "", ""},
                }},
            }
        },
        RPCExamples{
            "\nCreate a PQ multisig address from 2 ML-DSA public keys\n"
            + HelpExampleCli("createmultisig", "2 \"[\\\"<mldsa_key_hex_1>\\\",\\\"<mldsa_key_hex_2>\\\"]\"") +
            "\nAs a JSON-RPC call\n"
            + HelpExampleRpc("createmultisig", "2, [\"<mldsa_key_hex_1>\",\"<mldsa_key_hex_2>\"]")
                },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            const int required = request.params[0].getInt<int>();
            bool sort = false;
            std::optional<OutputType> output_type = OutputType::P2MR;

            if (request.params[2].isStr()) {
                output_type = ParseOutputType(request.params[2].get_str());
                if (!output_type) {
                    throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("Unknown address type '%s'", request.params[2].get_str()));
                }
            } else if (!request.params[2].isNull()) {
                const UniValue& options = request.params[2].get_obj();
                RPCTypeCheckObj(options,
                    {
                        {"address_type", UniValueType(UniValue::VSTR)},
                        {"sort", UniValueType(UniValue::VBOOL)},
                    },
                    true, true);
                if (options.exists("address_type")) {
                    output_type = ParseOutputType(options["address_type"].get_str());
                    if (!output_type) {
                        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("Unknown address type '%s'", options["address_type"].get_str()));
                    }
                }
                if (options.exists("sort")) {
                    sort = options["sort"].get_bool();
                }
            }

            if (!output_type || *output_type != OutputType::P2MR) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "Only address type 'p2mr' is supported for PQ multisig");
            }

            const UniValue& keys_param = request.params[1].get_array();
            std::vector<PQMultisigKey> parsed_keys;
            parsed_keys.reserve(keys_param.size());
            std::string error;
            for (unsigned int i = 0; i < keys_param.size(); ++i) {
                PQMultisigKey key;
                if (!ParsePQMultisigKeyString(keys_param[i].get_str(), key, error)) {
                    throw JSONRPCError(RPC_INVALID_PARAMETER, LEGACY_MULTISIG_DISABLED_ERROR);
                }
                parsed_keys.push_back(std::move(key));
            }

            if (parsed_keys.size() < 2) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "multisig requires at least 2 keys");
            }
            if (required < 1) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "nrequired must be at least 1");
            }
            if (static_cast<size_t>(required) > parsed_keys.size()) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "nrequired cannot exceed number of keys");
            }

            if (sort) {
                std::sort(parsed_keys.begin(), parsed_keys.end(), [](const auto& lhs, const auto& rhs) {
                    return lhs.pubkey < rhs.pubkey;
                });
            }

            std::vector<std::pair<PQAlgorithm, std::vector<unsigned char>>> script_keys;
            script_keys.reserve(parsed_keys.size());
            for (const auto& key : parsed_keys) {
                script_keys.emplace_back(key.algo, key.pubkey);
            }
            const std::vector<unsigned char> leaf_script = BuildP2MRMultisigScript(static_cast<uint8_t>(required), script_keys);
            if (leaf_script.empty()) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "Unable to build PQ multisig leaf script");
            }

            const uint256 leaf_hash = ComputeP2MRLeafHash(P2MR_LEAF_VERSION, leaf_script);
            const uint256 merkle_root = ComputeP2MRMerkleRoot({leaf_hash});
            const CTxDestination dest = WitnessV2P2MR{merkle_root};

            std::string descriptor = strprintf("mr(%s(%d", sort ? "sortedmulti_pq" : "multi_pq", required);
            for (const auto& key : parsed_keys) {
                descriptor += "," + RenderPQMultisigKey(key);
            }
            descriptor += "))";
            descriptor = AddChecksum(descriptor);

            UniValue result(UniValue::VOBJ);
            result.pushKV("address", EncodeDestination(dest));
            result.pushKV("redeemScript", HexStr(leaf_script));
            result.pushKV("descriptor", descriptor);
            return result;
        },
    };
}

static RPCHelpMan getdescriptorinfo()
{
    const std::string EXAMPLE_DESCRIPTOR = "wpkh([d34db33f/84h/0h/0h]0279be667ef9dcbbac55a06295Ce870b07029Bfcdb2dce28d959f2815b16f81798)";

    return RPCHelpMan{"getdescriptorinfo",
        {"\nAnalyses a descriptor.\n"},
        {
            {"descriptor", RPCArg::Type::STR, RPCArg::Optional::NO, "The descriptor."},
            {"options", RPCArg::Type::OBJ_NAMED_PARAMS, RPCArg::Optional::OMITTED, "",
                {
                    {"allow_op_success", RPCArg::Type::BOOL, RPCArg::Default{false}, "Allow P2MR-only OP_SUCCESS opcodes (0xbb-0xc2) inside tr() leaves. Unsafe; use for intentional testing only."},
                },
                RPCArgOptions{.oneline_description="options"}
            },
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "",
            {
                {RPCResult::Type::STR, "descriptor", "The descriptor in canonical form, without private keys. For a multipath descriptor, only the first will be returned."},
                {RPCResult::Type::ARR, "multipath_expansion", /*optional=*/true, "All descriptors produced by expanding multipath derivation elements. Only if the provided descriptor specifies multipath derivation elements.",
                {
                    {RPCResult::Type::STR, "", ""},
                }},
                {RPCResult::Type::STR, "checksum", "The checksum for the input descriptor"},
                {RPCResult::Type::BOOL, "isrange", "Whether the descriptor is ranged"},
                {RPCResult::Type::BOOL, "issolvable", "Whether the descriptor is solvable"},
                {RPCResult::Type::BOOL, "hasprivatekeys", "Whether the input descriptor contained at least one private key"},
            }
        },
        RPCExamples{
            "Analyse a descriptor\n" +
            HelpExampleCli("getdescriptorinfo", "\"" + EXAMPLE_DESCRIPTOR + "\"") +
            HelpExampleRpc("getdescriptorinfo", "\"" + EXAMPLE_DESCRIPTOR + "\"")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            DescriptorParseOptions parse_opts;
            if (request.params.size() > 1 && !request.params[1].isNull()) {
                const UniValue& options = request.params[1];
                RPCTypeCheckObj(options,
                    {
                        {"allow_op_success", UniValueType(UniValue::VBOOL)},
                    },
                    /*fAllowNull=*/true, /*fStrict=*/true);
                if (options.exists("allow_op_success")) {
                    parse_opts.allow_p2tr_op_success = options["allow_op_success"].get_bool();
                }
            }

            FlatSigningProvider provider;
            std::string error;
            auto descs = Parse(request.params[0].get_str(), provider, error, /*require_checksum=*/false, parse_opts);
            if (descs.empty()) {
                throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, error);
            }

            UniValue result(UniValue::VOBJ);
            result.pushKV("descriptor", descs.at(0)->ToString());

            if (descs.size() > 1) {
                UniValue multipath_descs(UniValue::VARR);
                for (const auto& d : descs) {
                    multipath_descs.push_back(d->ToString());
                }
                result.pushKV("multipath_expansion", multipath_descs);
            }

            result.pushKV("checksum", GetDescriptorChecksum(request.params[0].get_str()));
            result.pushKV("isrange", descs.at(0)->IsRange());
            result.pushKV("issolvable", descs.at(0)->IsSolvable());
            result.pushKV("hasprivatekeys", provider.keys.size() > 0);
            return result;
        },
    };
}

static UniValue DeriveAddresses(const Descriptor* desc, int64_t range_begin, int64_t range_end, FlatSigningProvider& key_provider)
{
    UniValue addresses(UniValue::VARR);

    for (int64_t i = range_begin; i <= range_end; ++i) {
        FlatSigningProvider provider;
        std::vector<CScript> scripts;
        if (!desc->Expand(i, key_provider, scripts, provider)) {
            const auto output_type = desc->GetOutputType();
            if (output_type && *output_type == OutputType::P2MR) {
                throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY,
                    "Cannot derive P2MR script without corresponding private keys. "
                    "Ranged mr() descriptors require private keys to derive PQ public keys; "
                    "xpub-only/watch-only descriptors are unsupported.");
            }
            throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Cannot derive script without private keys");
        }

        for (const CScript& script : scripts) {
            CTxDestination dest;
            if (!ExtractDestination(script, dest)) {
                // ExtractDestination no longer returns true for P2PK since it doesn't have a corresponding address
                // However combo will output P2PK and should just ignore that script
                if (scripts.size() > 1 && std::get_if<PubKeyDestination>(&dest)) {
                    continue;
                }
                throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Descriptor does not have a corresponding address");
            }

            addresses.push_back(EncodeDestination(dest));
        }
    }

    // This should not be possible, but an assert seems overkill:
    if (addresses.empty()) {
        throw JSONRPCError(RPC_MISC_ERROR, "Unexpected empty result");
    }

    return addresses;
}

static RPCHelpMan deriveaddresses()
{
    const std::string EXAMPLE_DESCRIPTOR = "wpkh([d34db33f/84h/0h/0h]xpub6DJ2dNUysrn5Vt36jH2KLBT2i1auw1tTSSomg8PhqNiUtx8QX2SvC9nrHu81fT41fvDUnhMjEzQgXnQjKEu3oaqMSzhSrHMxyyoEAmUHQbY/0/*)#cjjspncu";

    return RPCHelpMan{"deriveaddresses",
        {"\nDerives one or more addresses corresponding to an output descriptor.\n"
         "Examples of output descriptors are:\n"
         "    pkh(<pubkey>)                                     P2PKH outputs for the given pubkey\n"
         "    wpkh(<pubkey>)                                    Native segwit P2PKH outputs for the given pubkey\n"
         "    sh(multi(<n>,<pubkey>,<pubkey>,...))              P2SH-multisig outputs for the given threshold and pubkeys\n"
         "    raw(<hex script>)                                 Outputs whose output script equals the specified hex-encoded bytes\n"
         "    tr(<pubkey>,multi_a(<n>,<pubkey>,<pubkey>,...))   P2TR-multisig outputs for the given threshold and pubkeys\n"
         "\nIn the above, <pubkey> either refers to a fixed public key in hexadecimal notation, or to an xpub/xprv optionally followed by one\n"
         "or more path elements separated by \"/\", where \"h\" represents a hardened child key.\n"
         "For more information on output descriptors, see the documentation in the doc/descriptors.md file.\n"},
        {
            {"descriptor", RPCArg::Type::STR, RPCArg::Optional::NO, "The descriptor."},
            {"range", RPCArg::Type::RANGE, RPCArg::Optional::OMITTED, "If a ranged descriptor is used, this specifies the end or the range (in [begin,end] notation) to derive."},
            {"options", RPCArg::Type::OBJ_NAMED_PARAMS, RPCArg::Optional::OMITTED, "",
                {
                    {"require_checksum", RPCArg::Type::BOOL, RPCArg::Default{true}, "Require a checksum. If a checksum is provided it will be verified regardless of this parameter."},
                    {"allow_op_success", RPCArg::Type::BOOL, RPCArg::Default{false}, "Allow P2MR-only OP_SUCCESS opcodes (0xbb-0xc2) inside tr() leaves. Unsafe; use for intentional testing only."},
                },
                RPCArgOptions{.oneline_description="options"}
            },
        },
        {
            RPCResult{"for single derivation descriptors",
                RPCResult::Type::ARR, "", "",
                {
                    {RPCResult::Type::STR, "address", "the derived addresses"},
                }
            },
            RPCResult{"for multipath descriptors",
                RPCResult::Type::ARR, "", "The derived addresses for each of the multipath expansions of the descriptor, in multipath specifier order",
                {
                    {
                        RPCResult::Type::ARR, "", "The derived addresses for a multipath descriptor expansion",
                        {
                            {RPCResult::Type::STR, "address", "the derived address"},
                        },
                    },
                },
            },
        },
        RPCExamples{
            "First three native segwit receive addresses:\n" +
            HelpExampleCli("deriveaddresses", "\"" + EXAMPLE_DESCRIPTOR + "\" \"[0,2]\"") +
            HelpExampleRpc("deriveaddresses", "\"" + EXAMPLE_DESCRIPTOR + "\", \"[0,2]\"") +
            "Derive the PKH address from a WIF, which has a built-in checksum:\n" +
            HelpExampleCli("deriveaddresses", "\"pkh(cPsQTSmMZ8e3AEUWGjS73f5R364yJxH6RxcgnwbHjbKbFPUP2Dtu)\" null '{\"require_checksum\": false}'")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            const std::string desc_str = request.params[0].get_str();
            bool require_checksum = true;
            DescriptorParseOptions parse_opts;

            if (!request.params[2].isNull()) {
                const UniValue& options = request.params[2];
                RPCTypeCheckObj(options,
                    {
                        {"require_checksum", UniValueType(UniValue::VBOOL)},
                        {"allow_op_success", UniValueType(UniValue::VBOOL)},
                    },
                    true, true);

                if (options.exists("require_checksum")) {
                    require_checksum = options["require_checksum"].get_bool();
                }
                if (options.exists("allow_op_success")) {
                    parse_opts.allow_p2tr_op_success = options["allow_op_success"].get_bool();
                }
            }

            int64_t range_begin = 0;
            int64_t range_end = 0;

            if (request.params.size() >= 2 && !request.params[1].isNull()) {
                std::tie(range_begin, range_end) = ParseDescriptorRange(request.params[1]);
            }

            FlatSigningProvider key_provider;
            std::string error;
            auto descs = Parse(desc_str, key_provider, error, require_checksum, parse_opts);
            if (descs.empty()) {
                throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, error);
            }
            auto& desc = descs.at(0);
            if (!desc->IsRange() && !request.params[1].isNull()) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "Range should not be specified for an un-ranged descriptor");
            }

            if (desc->IsRange() && request.params[1].isNull()) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "Range must be specified for a ranged descriptor");
            }

            UniValue addresses = DeriveAddresses(desc.get(), range_begin, range_end, key_provider);

            if (descs.size() == 1) {
                return addresses;
            }

            UniValue ret(UniValue::VARR);
            ret.push_back(addresses);
            for (size_t i = 1; i < descs.size(); ++i) {
                ret.push_back(DeriveAddresses(descs.at(i).get(), range_begin, range_end, key_provider));
            }
            return ret;
        },
    };
}

void RegisterOutputScriptRPCCommands(CRPCTable& t)
{
    static const CRPCCommand commands[]{
        {"util", &validateaddress},
        {"util", &createmultisig},
        {"util", &deriveaddresses},
        {"util", &getdescriptorinfo},
    };
    for (const auto& c : commands) {
        t.appendCommand(c.name, &c);
    }
}
