#!/usr/bin/env python3
"""Apply generated BTX assumeutxo metadata into chainparams.cpp.

This helper consumes the JSON report emitted by
`contrib/devtools/generate_assumeutxo.py` and merges the target chain's
`m_assumeutxo_data` block without hand-editing `src/kernel/chainparams.cpp`.

The script is intentionally conservative:
 - it validates the report shape before touching any source file
 - it only rewrites the requested chain class
 - it preserves existing heights by default and appends the new entry in
   ascending-height order
 - it refuses to overwrite a conflicting existing height unless
   `--replace-existing` is passed explicitly
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any


HEX64_RE = re.compile(r"^[0-9a-f]{64}$")
ENTRY_RE = re.compile(
    r"""
    \{
        \s*
        (?:
            // [^\n]* \n \s*
        )*
        \.height \s* = \s* (?P<height>[0-9']+) \s* ,
        \s*
        \.hash_serialized \s* = \s* AssumeutxoHash\{uint256\{"(?P<txoutset_hash>[0-9a-f]{64})"\}\} \s* ,
        \s*
        \.m_chain_tx_count \s* = \s* (?P<nchaintx>[0-9']+) \s* ,
        \s*
        \.blockhash \s* = \s* consteval_ctor\(uint256\{"(?P<blockhash>[0-9a-f]{64})"\}\) \s* ,
        \s*
    \}
    """,
    re.VERBOSE | re.S,
)


class AssumeutxoApplyError(RuntimeError):
    pass


@dataclass(frozen=True)
class AssumeutxoSnapshot:
    chain: str
    height: int
    txoutset_hash: str
    nchaintx: int
    blockhash: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Apply generated assumeutxo metadata into chainparams.cpp."
    )
    parser.add_argument(
        "--report",
        type=Path,
        required=True,
        help="Path to the JSON report generated by contrib/devtools/generate_assumeutxo.py.",
    )
    parser.add_argument(
        "--chainparams",
        type=Path,
        default=Path("src/kernel/chainparams.cpp"),
        help="Path to chainparams.cpp (default: src/kernel/chainparams.cpp).",
    )
    parser.add_argument(
        "--chain",
        choices=("main", "testnet", "testnet4", "signet", "regtest", "shieldedv2dev"),
        default=None,
        help="Chain class to update. Defaults to the chain value from the report.",
    )
    parser.add_argument(
        "--allow-non-empty",
        action="store_true",
        help="Deprecated alias for --replace-existing.",
    )
    parser.add_argument(
        "--replace-existing",
        action="store_true",
        help="Allow overwriting a conflicting existing height in m_assumeutxo_data.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only verify that chainparams already matches the generated metadata.",
    )
    return parser.parse_args()


def parse_hex64(value: Any, field: str) -> str:
    if not isinstance(value, str):
        raise AssumeutxoApplyError(f"{field} must be a string")
    normalized = value.strip().lower()
    if not HEX64_RE.fullmatch(normalized):
        raise AssumeutxoApplyError(f"{field} must be a 64-char lowercase hex hash")
    return normalized


def parse_report(path: Path) -> tuple[AssumeutxoSnapshot, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise AssumeutxoApplyError("report root must be a JSON object")

    chain = data.get("chain")
    if not isinstance(chain, str) or not chain:
        raise AssumeutxoApplyError("report field `chain` is required")

    snapshot_data = data.get("snapshot")
    if snapshot_data is None:
        snapshot_data = data
    if not isinstance(snapshot_data, dict):
        raise AssumeutxoApplyError("report field `snapshot` must be a JSON object when present")

    height = snapshot_data.get("height")
    txoutset_hash = snapshot_data.get("txoutset_hash")
    nchaintx = snapshot_data.get("nchaintx")
    blockhash = snapshot_data.get("blockhash")

    if not isinstance(height, int) or height < 0:
        raise AssumeutxoApplyError("snapshot.height must be a non-negative integer")
    if not isinstance(nchaintx, int) or nchaintx < 0:
        raise AssumeutxoApplyError("snapshot.nchaintx must be a non-negative integer")

    snapshot = AssumeutxoSnapshot(
        chain=chain,
        height=height,
        txoutset_hash=parse_hex64(txoutset_hash, "snapshot.txoutset_hash"),
        nchaintx=nchaintx,
        blockhash=parse_hex64(blockhash, "snapshot.blockhash"),
    )
    return snapshot, chain


def format_int_with_ticks(value: int) -> str:
    text = str(value)
    groups: list[str] = []
    while text:
        groups.append(text[-3:])
        text = text[:-3]
    return "'".join(reversed(groups))


def class_name_for_chain(chain: str) -> str:
    mapping = {
        "main": "CMainParams",
        "testnet": "CTestNetParams",
        "testnet4": "CTestNet4Params",
        "signet": "SigNetParams",
        "regtest": "CRegTestParams",
        "shieldedv2dev": "CShieldedV2DevParams",
    }
    try:
        return mapping[chain]
    except KeyError as exc:
        raise AssumeutxoApplyError(f"unsupported chain `{chain}`") from exc


def parse_int_with_ticks(value: str, field: str) -> int:
    normalized = value.replace("'", "")
    if not normalized.isdigit():
        raise AssumeutxoApplyError(f"{field} must be an integer literal")
    return int(normalized)


def parse_existing_assumeutxo_entries(assignment: str, chain: str) -> list[AssumeutxoSnapshot]:
    if re.fullmatch(r"(?ms)\s*m_assumeutxo_data\s*=\s*\{\s*\};\s*", assignment):
        return []

    entries: list[AssumeutxoSnapshot] = []
    for match in ENTRY_RE.finditer(assignment):
        entries.append(
            AssumeutxoSnapshot(
                chain=chain,
                height=parse_int_with_ticks(match.group("height"), "existing height"),
                txoutset_hash=match.group("txoutset_hash"),
                nchaintx=parse_int_with_ticks(match.group("nchaintx"), "existing m_chain_tx_count"),
                blockhash=match.group("blockhash"),
            )
        )

    if not entries:
        raise AssumeutxoApplyError("unable to parse existing m_assumeutxo_data entries")
    return sorted(entries, key=lambda entry: entry.height)


def build_chainparams_assignment(chain: str, entries: list[AssumeutxoSnapshot]) -> str:
    if not entries:
        return "m_assumeutxo_data = {};"

    lines = ["m_assumeutxo_data = {"]
    for entry in sorted(entries, key=lambda item: item.height):
        lines.extend(
            [
                "    {",
                f"        // {chain} assumeutxo snapshot at height {format_int_with_ticks(entry.height)}",
                f"        .height = {format_int_with_ticks(entry.height)},",
                f"        .hash_serialized = AssumeutxoHash{{uint256{{\"{entry.txoutset_hash}\"}}}},",
                f"        .m_chain_tx_count = {format_int_with_ticks(entry.nchaintx)},",
                f"        .blockhash = consteval_ctor(uint256{{\"{entry.blockhash}\"}}),",
                "    },",
            ]
        )
    lines.append("};")
    return "\n".join(lines)


def merge_assumeutxo_entries(
    chain: str,
    existing_entries: list[AssumeutxoSnapshot],
    snapshot: AssumeutxoSnapshot,
    replace_existing: bool,
) -> list[AssumeutxoSnapshot]:
    merged = {entry.height: entry for entry in existing_entries}
    current = merged.get(snapshot.height)
    if current is None:
        merged[snapshot.height] = snapshot
    elif current != snapshot:
        if not replace_existing:
            raise AssumeutxoApplyError(
                f"{chain} already has assumeutxo metadata at height {snapshot.height}; "
                "pass --replace-existing to overwrite that entry"
            )
        merged[snapshot.height] = snapshot
    return [merged[height] for height in sorted(merged)]


def replace_assumeutxo_block(
    source: str,
    chain: str,
    snapshot: AssumeutxoSnapshot,
    replace_existing: bool,
) -> str:
    class_name = class_name_for_chain(chain)
    class_pattern = rf"class {class_name} : public CChainParams \{{.*?\n\}};\n"
    class_match = re.search(class_pattern, source, flags=re.S)
    if not class_match:
        raise AssumeutxoApplyError(f"unable to locate class block for {class_name}")

    original_block = class_match.group(0)
    assignment_re = re.compile(r"(?ms)^(?P<indent>\s*)m_assumeutxo_data\s*=\s*\{.*?\};")
    assignment_match = assignment_re.search(original_block)
    if not assignment_match:
        raise AssumeutxoApplyError(f"unable to locate m_assumeutxo_data assignment in {class_name}")

    existing_assignment = assignment_match.group(0)
    existing_entries = parse_existing_assumeutxo_entries(existing_assignment, chain)
    merged_entries = merge_assumeutxo_entries(chain, existing_entries, snapshot, replace_existing)

    indent = assignment_match.group("indent")
    replacement = textwrap.indent(build_chainparams_assignment(chain, merged_entries), indent)
    updated_block = original_block[:assignment_match.start()] + replacement + original_block[assignment_match.end():]
    return source.replace(original_block, updated_block, 1)


def main() -> int:
    args = parse_args()
    try:
        snapshot, report_chain = parse_report(args.report)
        chain = args.chain or report_chain
        if chain != report_chain:
            raise AssumeutxoApplyError(
                f"report chain `{report_chain}` does not match --chain `{chain}`"
            )
        replace_existing = args.replace_existing or args.allow_non_empty

        source = args.chainparams.read_text(encoding="utf-8")
        updated_source = replace_assumeutxo_block(
            source,
            chain,
            snapshot,
            replace_existing or args.check,
        )

        if args.check:
            if updated_source != source:
                print(
                    "error: chainparams does not match generated assumeutxo metadata",
                    file=sys.stderr,
                )
                return 1
            print("assumeutxo apply check: PASS")
            return 0

        if updated_source != source:
            args.chainparams.write_text(updated_source, encoding="utf-8")
        print(f"updated {args.chainparams} for chain {chain}")
        return 0
    except (AssumeutxoApplyError, OSError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
