#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the BTX network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x92,0xbe,0xb3,0x56,0x4b,0x87,
    0x01,0x04,0xa4,0x5a,0xf6,0xe5,0x4b,0x87,
};

// chainparams_seed_signet: no entries

// chainparams_seed_test: no entries

// chainparams_seed_testnet4: no entries
#endif // BITCOIN_CHAINPARAMSSEEDS_H
